# -*- coding: utf-8 -*-
"""
    Normal settings file for Eve.

    Differently from a configuration file for an Eve application backed by Mongo
    we need to define the schema using the registerSchema decorator.

"""
from eve.io.sql.decorators import registerSchema
from tables import Address, Geoposition, Site, Evaluation, Person, SiteMaintainer

registerSchema('address')(Address)
registerSchema('geoposition')(Geoposition)
registerSchema('site')(Site)
registerSchema('evaluation')(Evaluation)
registerSchema('person')(Person)
registerSchema('site_maintainer')(SiteMaintainer)

SQLALCHEMY_DATABASE_URI = 'postgres://eve:test_bmp@localhost/test_bmp'

# The following two lines will output the SQL statements executed by SQLAlchemy. Useful while debugging
# and in development. Turned off by default
# --------
# SQLALCHEMY_ECHO = True
# SQLALCHEMY_RECORD_QUERIES = True

DEBUG = True

# The default schema is generated by the decorator
DOMAIN = {
    'address': Address._eve_schema['address'],
    'geoposition': Geoposition._eve_schema['geoposition'],
    'site': Site._eve_schema['site'],
    'evaluation': Evaluation._eve_schema['evaluation'],
    'person': Person._eve_schema['person']
    }

# but you can always customize it:
DOMAIN['address'].update({
    'item_title': 'person',
    'additional_lookup': {
        'url': '[0-9]+',
        'field': 'id'
        },
    'cache_control': 'max-age=10,must-revalidate',
    'cache_expires': 10,
    'resource_methods': ['GET', 'POST', 'DELETE']
    })
